openapi: 3.0.0
info:
  title : API_users
  version : 1.0.0
  description: API de gestion des utilisateurs
  contact:
    name: Amaury Cournac
    email: amaury.cournac@etudiant.univ-rennes1.fr
tags:
  - name: Users
    description: List of users and fonctions

components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nom:
          type: string
        prenom:
          type: string
        mail: 
          type: string
        pseudo:
          type: string

paths:
  /users:
    post:
      tags:
        - Users
      summary: Créer un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Récupérer les informations d'un utilisateur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Informations de l'utilisateur récupérées avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '404':
          description: Utilisateur non trouvé

    put:
      tags:
        - Users
      summary: Mettre à jour les informations d'un utilisateur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
      responses:
        '200':
          description: Informations de l'utilisateur mises à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '404':
          description: Utilisateur non trouvé

    delete:
      tags:
        - Users
      summary: Supprimer un utilisateur
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Utilisateur supprimé avec succès
        '404':
          description: Utilisateur non trouvé
