services:
  postgres_database:  # Nom du service
    container_name: postgres_database  # Nom du conteneur Docker
    build: ./postgresql  # Chemin vers le répertoire contenant les fichiers de configuration pour construire l'image Docker
    restart: always  # Redémarrer le conteneur automatiquement en cas d'arrêt inattendu
    environment:  # Définition des variables d'environnement pour le conteneur
      - POSTGRES_PASSWORD=bonjour  # Définition de la variable d'environnement POSTGRES_PASSWORD avec la valeur "bonjour"
    ports:  # Définition du mappage des ports entre le système hôte et le conteneur
      - "6033:3306"  # Mappage du port 6033 du système hôte sur le port 3306 du conteneur PostgreSQL
